In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df1 = pd.read_csv('table1_clear.csv', encoding='big5')
df2 = pd.read_csv('table2_clear.csv', encoding='big5')
df5 = pd.read_csv('table5_clear.csv', encoding='big5')
df6 = pd.read_csv('table6_clear.csv', encoding='big5')
df10 = pd.read_csv('table10_clear.csv', encoding='big5')
df14 = pd.read_csv('table14_clear.csv', encoding='big5')

In [4]:
df1.shape, df2.shape, df5.shape, df6.shape, df10.shape, df14.shape

((88938, 5), (88938, 11), (7979, 9), (23425, 4), (88938, 9), (27968, 96))

順序: 14 -> 1 -> 2 -> 10 -> 6 -> 5

In [5]:
data = pd.merge(df14, df1, on='ACCOUNTNO', how='left')
print(data.shape)
data = pd.merge(data, df2, on='ACCOUNTNO', how='left')
print(data.shape)
data = pd.merge(data, df10, on='ACCOUNTNO', how='left')
print(data.shape)
data = pd.merge(data, df6, on='ACCOUNTNO', how='left')
print(data.shape)
data = pd.merge(data, df5, on='ACCOUNTNO', how='left')
print(data.shape)

(27968, 100)
(27968, 110)
(27968, 118)
(27968, 121)
(27968, 129)

In [6]:
data

,ACCOUNTNO,Acyclovir,Amikacin,Amoxicillin,Amoxicillin/Clavulanic acid,Amphotericin B,Amphotericin B/liposome,Ampicillin,Ampicillin/Sulbactam,Anidulafungin,Azithromycin,Baloxavir marboxil,Cefadroxil,Cefazolin,Cefepime,Cefixime,Cefoperazone/sulbactam,Cefotaxime,Cefoxitin,Ceftazidime,Ceftazidime/Avibactam,Ceftizoxime,Ceftriaxone,Cefuroxime,Cephalexin,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Dicloxacillin,Doripenem,Doxycycline,Ertapenem,Erythromycin,Ethambutol,Famciclovir,Fenticonazole,Fidaxomicin,Flomoxef,Fluconazole,Flucytosine,Fosfomycin,Ganciclovir,Gentamicin,Griseofulvin,Imipenem/Cilastatin,Isoniazid,Itraconazole,Lamivudine/Dolutegravir,Levofloxacin,Linezolid,Meropenem,Metronidazole,Micafungin,Minocycline,Moxifloxacin,Nemonoxacin,Nystatin,Oseltamivir,Oxacillin,Penicillin,Peramivir,Pipemidic acid,Piperacillin/Tazobactam,Posaconazole,Pyrazinamide,Rifabutin,Rifampin,Rifampin/Isoniazid/Ethambutol,Sofosbuvir/Velpatasvir,Streptomycin,Sulfamethoxazole/Trimethoprim,Teicoplanin,Telbivudine,Tenofovir,Tenofovir alafenamide,Terbinafine,Tetracycline,Valaciclovir,Valganciclovir,Vancomycin,Voriconazole,Zanamivir,abacavir/lamivudine/dolutegravir,ifampin/Isoniazid,tenofovir/emtricitabine,tenofovir/emtricitabine/bictegravir,tenofovir/emtricitabine/rilpivirine,AUTIBIOTIC_GROUP,INFECTIONSITE1,INFECTIONSITE2,INFECTIONSITE3,INFECTIONSITE4,INFECTIONSITE5,INFECTIONSITE9,OTHERINFECTIONSITE_flag,ROOMNO,AGE,SEX,STAYTIME,ISSEPSIS0,VITALSIGNSBT,VITALSIGNSPR,VITALSIGNSRR,VITALSIGNSSPO2,VITALSIGNSDBP,VITALSIGNSGCS,MAP,FEVER,INJURELEVEL,DM,CARDIOVASCULAR,RESPIRATORY,CNS,CANCER,LIVER,KIDNEY,AUTOIMMUNE,WBC,Lymphocyte,CRP,CHECKITEM28A,CHECKITEM27,CHECKITEM27SCORE,CHECKITEM28SCORE,CHECKITEM29SCORE,CHECKITEM30SCORE,CHECKITEM31SCORE,CHECKITEM32SCORE
0,I11300000002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,65.0,M,807.0,N,38.2,106.0,20.0,95.0,93.0,15.0,113.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I11300000003,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,C,48.0,F,17.0,N,36.4,88.0,20.0,NaN,85.0,15.0,105.0,Y,4.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I11300000008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,19.0,F,178.0,N,37.6,120.0,18.0,NaN,62.0,15.0,73.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I11300000011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,16.0,M,72.0,N,36.3,118.0,18.0,NaN,64.0,15.0,77.0,Y,3.0,N,N,Y,N,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I11300000014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,22.0,F,92.0,N,36.9,103.0,18.0,NaN,61.0,15.0,74.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27963,I11400060686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,45.0,M,718.0,N,35.6,112.0,22.0,100.0,90.0,15.0,104.0,Y,3.0,N,N,N,N,N,N,N,N,7.49,15.2,1.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27964,I11400060687,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,1,0,0,0,0,0,A,82.0,M,297.0,N,36.0,87.0,20.0,98.0,58.0,15.0,74.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,15.08,10.1,3.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27965,I11400060701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,1,0,0,0,0,0,A,68.0,M,1097.0,N,36.4,82.0,28.0,96.0,100.0,15.0,121.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,8.41,14.5,3.674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27966,I11400060720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,71.0,M,790.0,N,35.8,111.0,26.0,100.0,119.0,15.0,146.0,Y,2.0,Y,Y,Y,Y,N,Y,N,Y,11.48,13.2,0.815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27967,I11400060731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,62.0,M,734.0,Y,35.7,92.0,20.0,97.0,53.0,14.0,60.0,Y,2.0,N,N,Y,Y,Y,Y,Y,Y,12.42,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print(data.nunique())

ACCOUNTNO                      27968
Acyclovir                          2
Amikacin                           2
Amoxicillin                        2
Amoxicillin/Clavulanic acid        2
                               ...
CHECKITEM28SCORE                   5
CHECKITEM29SCORE                   5
CHECKITEM30SCORE                   4
CHECKITEM31SCORE                   5
CHECKITEM32SCORE                   5
Length: 129, dtype: int64

In [8]:
data.columns

Index(['ACCOUNTNO', 'Acyclovir', 'Amikacin', 'Amoxicillin',
       'Amoxicillin/Clavulanic acid', 'Amphotericin B',
       'Amphotericin B/liposome', 'Ampicillin', 'Ampicillin/Sulbactam',
       'Anidulafungin',
       ...
       'Lymphocyte', 'CRP', 'CHECKITEM28A', 'CHECKITEM27', 'CHECKITEM27SCORE',
       'CHECKITEM28SCORE', 'CHECKITEM29SCORE', 'CHECKITEM30SCORE',
       'CHECKITEM31SCORE', 'CHECKITEM32SCORE'],
      dtype='object', length=129)

過濾掉所有抗生素都沒開的人

In [9]:
data.to_csv('anti_total.csv', index=False)

In [10]:
data # target: Acyclovir ~ tenofovir/emtricitabine/rilpivirine

,ACCOUNTNO,Acyclovir,Amikacin,Amoxicillin,Amoxicillin/Clavulanic acid,Amphotericin B,Amphotericin B/liposome,Ampicillin,Ampicillin/Sulbactam,Anidulafungin,Azithromycin,Baloxavir marboxil,Cefadroxil,Cefazolin,Cefepime,Cefixime,Cefoperazone/sulbactam,Cefotaxime,Cefoxitin,Ceftazidime,Ceftazidime/Avibactam,Ceftizoxime,Ceftriaxone,Cefuroxime,Cephalexin,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Dicloxacillin,Doripenem,Doxycycline,Ertapenem,Erythromycin,Ethambutol,Famciclovir,Fenticonazole,Fidaxomicin,Flomoxef,Fluconazole,Flucytosine,Fosfomycin,Ganciclovir,Gentamicin,Griseofulvin,Imipenem/Cilastatin,Isoniazid,Itraconazole,Lamivudine/Dolutegravir,Levofloxacin,Linezolid,Meropenem,Metronidazole,Micafungin,Minocycline,Moxifloxacin,Nemonoxacin,Nystatin,Oseltamivir,Oxacillin,Penicillin,Peramivir,Pipemidic acid,Piperacillin/Tazobactam,Posaconazole,Pyrazinamide,Rifabutin,Rifampin,Rifampin/Isoniazid/Ethambutol,Sofosbuvir/Velpatasvir,Streptomycin,Sulfamethoxazole/Trimethoprim,Teicoplanin,Telbivudine,Tenofovir,Tenofovir alafenamide,Terbinafine,Tetracycline,Valaciclovir,Valganciclovir,Vancomycin,Voriconazole,Zanamivir,abacavir/lamivudine/dolutegravir,ifampin/Isoniazid,tenofovir/emtricitabine,tenofovir/emtricitabine/bictegravir,tenofovir/emtricitabine/rilpivirine,AUTIBIOTIC_GROUP,INFECTIONSITE1,INFECTIONSITE2,INFECTIONSITE3,INFECTIONSITE4,INFECTIONSITE5,INFECTIONSITE9,OTHERINFECTIONSITE_flag,ROOMNO,AGE,SEX,STAYTIME,ISSEPSIS0,VITALSIGNSBT,VITALSIGNSPR,VITALSIGNSRR,VITALSIGNSSPO2,VITALSIGNSDBP,VITALSIGNSGCS,MAP,FEVER,INJURELEVEL,DM,CARDIOVASCULAR,RESPIRATORY,CNS,CANCER,LIVER,KIDNEY,AUTOIMMUNE,WBC,Lymphocyte,CRP,CHECKITEM28A,CHECKITEM27,CHECKITEM27SCORE,CHECKITEM28SCORE,CHECKITEM29SCORE,CHECKITEM30SCORE,CHECKITEM31SCORE,CHECKITEM32SCORE
0,I11300000002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,65.0,M,807.0,N,38.2,106.0,20.0,95.0,93.0,15.0,113.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,I11300000003,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,C,48.0,F,17.0,N,36.4,88.0,20.0,NaN,85.0,15.0,105.0,Y,4.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,I11300000008,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,19.0,F,178.0,N,37.6,120.0,18.0,NaN,62.0,15.0,73.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,I11300000011,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,16.0,M,72.0,N,36.3,118.0,18.0,NaN,64.0,15.0,77.0,Y,3.0,N,N,Y,N,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,I11300000014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,0,0,0,0,0,0,A,22.0,F,92.0,N,36.9,103.0,18.0,NaN,61.0,15.0,74.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27963,I11400060686,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,45.0,M,718.0,N,35.6,112.0,22.0,100.0,90.0,15.0,104.0,Y,3.0,N,N,N,N,N,N,N,N,7.49,15.2,1.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27964,I11400060687,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,1,0,0,0,0,0,A,82.0,M,297.0,N,36.0,87.0,20.0,98.0,58.0,15.0,74.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,15.08,10.1,3.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27965,I11400060701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0,1,0,0,0,0,0,A,68.0,M,1097.0,N,36.4,82.0,28.0,96.0,100.0,15.0,121.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,8.41,14.5,3.674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27966,I11400060720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,71.0,M,790.0,N,35.8,111.0,26.0,100.0,119.0,15.0,146.0,Y,2.0,Y,Y,Y,Y,N,Y,N,Y,11.48,13.2,0.815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27967,I11400060731,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,1,0,0,0,0,0,0,A,62.0,M,734.0,Y,35.7,92.0,20.0,97.0,53.0,14.0,60.0,Y,2.0,N,N,Y,Y,Y,Y,Y,Y,12.42,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
select_cols = data.columns.get_loc('tenofovir/emtricitabine/rilpivirine')

X = data.iloc[:, select_cols + 1:]

In [12]:
X.columns

Index(['AUTIBIOTIC_GROUP', 'INFECTIONSITE1', 'INFECTIONSITE2',
       'INFECTIONSITE3', 'INFECTIONSITE4', 'INFECTIONSITE5', 'INFECTIONSITE9',
       'OTHERINFECTIONSITE_flag', 'ROOMNO', 'AGE', 'SEX', 'STAYTIME',
       'ISSEPSIS0', 'VITALSIGNSBT', 'VITALSIGNSPR', 'VITALSIGNSRR',
       'VITALSIGNSSPO2', 'VITALSIGNSDBP', 'VITALSIGNSGCS', 'MAP', 'FEVER',
       'INJURELEVEL', 'DM', 'CARDIOVASCULAR', 'RESPIRATORY', 'CNS', 'CANCER',
       'LIVER', 'KIDNEY', 'AUTOIMMUNE', 'WBC', 'Lymphocyte', 'CRP',
       'CHECKITEM28A', 'CHECKITEM27', 'CHECKITEM27SCORE', 'CHECKITEM28SCORE',
       'CHECKITEM29SCORE', 'CHECKITEM30SCORE', 'CHECKITEM31SCORE',
       'CHECKITEM32SCORE'],
      dtype='object')

In [13]:
X

,AUTIBIOTIC_GROUP,INFECTIONSITE1,INFECTIONSITE2,INFECTIONSITE3,INFECTIONSITE4,INFECTIONSITE5,INFECTIONSITE9,OTHERINFECTIONSITE_flag,ROOMNO,AGE,SEX,STAYTIME,ISSEPSIS0,VITALSIGNSBT,VITALSIGNSPR,VITALSIGNSRR,VITALSIGNSSPO2,VITALSIGNSDBP,VITALSIGNSGCS,MAP,FEVER,INJURELEVEL,DM,CARDIOVASCULAR,RESPIRATORY,CNS,CANCER,LIVER,KIDNEY,AUTOIMMUNE,WBC,Lymphocyte,CRP,CHECKITEM28A,CHECKITEM27,CHECKITEM27SCORE,CHECKITEM28SCORE,CHECKITEM29SCORE,CHECKITEM30SCORE,CHECKITEM31SCORE,CHECKITEM32SCORE
0,2,1,0,0,0,0,0,0,A,65.0,M,807.0,N,38.2,106.0,20.0,95.0,93.0,15.0,113.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0,0,0,0,0,0,0,C,48.0,F,17.0,N,36.4,88.0,20.0,NaN,85.0,15.0,105.0,Y,4.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,0,0,0,0,0,0,A,19.0,F,178.0,N,37.6,120.0,18.0,NaN,62.0,15.0,73.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,0,0,0,0,0,0,0,A,16.0,M,72.0,N,36.3,118.0,18.0,NaN,64.0,15.0,77.0,Y,3.0,N,N,Y,N,N,Y,Y,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,0,0,0,0,0,0,0,A,22.0,F,92.0,N,36.9,103.0,18.0,NaN,61.0,15.0,74.0,Y,3.0,N,N,N,N,N,N,N,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27963,2,1,0,0,0,0,0,0,A,45.0,M,718.0,N,35.6,112.0,22.0,100.0,90.0,15.0,104.0,Y,3.0,N,N,N,N,N,N,N,N,7.49,15.2,1.622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27964,2,0,1,0,0,0,0,0,A,82.0,M,297.0,N,36.0,87.0,20.0,98.0,58.0,15.0,74.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,15.08,10.1,3.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27965,2,0,1,0,0,0,0,0,A,68.0,M,1097.0,N,36.4,82.0,28.0,96.0,100.0,15.0,121.0,Y,3.0,N,Y,Y,Y,N,Y,Y,Y,8.41,14.5,3.674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27966,2,1,0,0,0,0,0,0,A,71.0,M,790.0,N,35.8,111.0,26.0,100.0,119.0,15.0,146.0,Y,2.0,Y,Y,Y,Y,N,Y,N,Y,11.48,13.2,0.815,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27967,2,1,0,0,0,0,0,0,A,62.0,M,734.0,Y,35.7,92.0,20.0,97.0,53.0,14.0,60.0,Y,2.0,N,N,Y,Y,Y,Y,Y,Y,12.42,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
Y = data.iloc[:, :select_cols + 1].drop(columns='ACCOUNTNO')

In [15]:
Y.columns, Y.shape

(Index(['Acyclovir', 'Amikacin', 'Amoxicillin', 'Amoxicillin/Clavulanic acid',
        'Amphotericin B', 'Amphotericin B/liposome', 'Ampicillin',
        'Ampicillin/Sulbactam', 'Anidulafungin', 'Azithromycin',
        'Baloxavir marboxil', 'Cefadroxil', 'Cefazolin', 'Cefepime', 'Cefixime',
        'Cefoperazone/sulbactam', 'Cefotaxime', 'Cefoxitin', 'Ceftazidime',
        'Ceftazidime/Avibactam', 'Ceftizoxime', 'Ceftriaxone', 'Cefuroxime',
        'Cephalexin', 'Ciprofloxacin', 'Clarithromycin', 'Clindamycin',
        'Colistin', 'Dicloxacillin', 'Doripenem', 'Doxycycline', 'Ertapenem',
        'Erythromycin', 'Ethambutol', 'Famciclovir', 'Fenticonazole',
        'Fidaxomicin', 'Flomoxef', 'Fluconazole', 'Flucytosine', 'Fosfomycin',
        'Ganciclovir', 'Gentamicin', 'Griseofulvin', 'Imipenem/Cilastatin',
        'Isoniazid', 'Itraconazole', 'Lamivudine/Dolutegravir', 'Levofloxacin',
        'Linezolid', 'Meropenem', 'Metronidazole', 'Micafungin', 'Minocycline',
        'Moxifloxacin', 'Nemonoxacin', 'Nystatin', 'Oseltamivir', 'Oxacillin',
        'Penicillin', 'Peramivir', 'Pipemidic acid', 'Piperacillin/Tazobactam',
        'Posaconazole', 'Pyrazinamide', 'Rifabutin', 'Rifampin',
        'Rifampin/Isoniazid/Ethambutol', 'Sofosbuvir/Velpatasvir',
        'Streptomycin', 'Sulfamethoxazole/Trimethoprim', 'Teicoplanin',
        'Telbivudine', 'Tenofovir', 'Tenofovir alafenamide', 'Terbinafine',
        'Tetracycline', 'Valaciclovir', 'Valganciclovir', 'Vancomycin',
        'Voriconazole', 'Zanamivir', 'abacavir/lamivudine/dolutegravir',
        'ifampin/Isoniazid', 'tenofovir/emtricitabine',
        'tenofovir/emtricitabine/bictegravir',
        'tenofovir/emtricitabine/rilpivirine'],
       dtype='object'),
 (27968, 87))

X:

In [16]:
features_with_na = [features for features in X.columns if X[features].isnull().sum() > 1]

for feature in features_with_na:
    print(feature, (X[feature].isnull().sum()/len(X[feature]) *100).round(1), '% missing values')

VITALSIGNSBT 1.1 % missing values
VITALSIGNSPR 4.0 % missing values
VITALSIGNSRR 3.9 % missing values
VITALSIGNSSPO2 25.1 % missing values
VITALSIGNSDBP 11.2 % missing values
VITALSIGNSGCS 1.5 % missing values
MAP 11.2 % missing values
WBC 67.6 % missing values
Lymphocyte 67.8 % missing values
CRP 74.3 % missing values
CHECKITEM28A 81.0 % missing values
CHECKITEM27 82.2 % missing values
CHECKITEM27SCORE 82.2 % missing values
CHECKITEM28SCORE 81.0 % missing values
CHECKITEM29SCORE 78.1 % missing values
CHECKITEM30SCORE 78.9 % missing values
CHECKITEM31SCORE 95.2 % missing values
CHECKITEM32SCORE 82.5 % missing values