In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df2024 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2024\2024Sepsis00101.csv', encoding='big5', dtype={'INTIME': str, 'EMGOUTTIME': str, 0: str})
df2025 = pd.read_csv(r'C:\Users\482525\Desktop\敗血症資料\2025\2025Sepsis00101.csv', encoding='big5', dtype={'INTIME': str, 'EMGOUTTIME': str, 0: str})

df2024['INTIME'] = pd.to_datetime(df2024['INTIME'], format='%Y%m%d%H%M%S', errors='coerce')
df2024['EMGOUTTIME'] = pd.to_datetime(df2024['EMGOUTTIME'], format='%Y%m%d%H%M%S', errors='coerce')
df2025['INTIME'] = pd.to_datetime(df2025['INTIME'], format='%Y%m%d%H%M%S', errors='coerce')
df2025['EMGOUTTIME'] = pd.to_datetime(df2025['EMGOUTTIME'], format='%Y%m%d%H%M%S', errors='coerce')

table1 = pd.concat([df2024, df2025], ignore_index=True)

In [3]:
table1 = table1.dropna(how='all')
table1 = table1[table1['ACCOUNTNO'].notna()]
table1 = table1.loc[:, ~table1.columns.str.contains('^Unnamed')]

In [4]:
table1

,DIVISIONNO,ACCOUNTNO,IPDACCOUNTNO,INTIME,ISEMGOUT,EMGOUTTIME,ROOMNO,AGE,SEX,STAYTIME,...,IPDINTIME,ISICU,ICUTIME,ISDEATH,DEATHTIME,ISBOOKICU,ISTRANS,TRANSTIME,NHIDISCHARGECODE,IPDNHIDISCHARGECODE
0,001,I11300000001,NaN,2024-01-01 00:44:57,Y,2024-01-01 01:08:30,C,57.0,F,23.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
1,001,I11300000002,I11300000176,2024-01-01 00:47:17,N,2024-01-01 14:14:21,A,65.0,M,807.0,...,2.024010e+13,N,NaN,N,NaN,N,N,NaN,Z,3
2,001,I11300000003,NaN,2024-01-01 00:50:21,Y,2024-01-01 01:07:31,C,48.0,F,17.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
3,001,I11300000004,NaN,2024-01-01 00:57:08,Y,2024-01-01 02:28:31,A,21.0,F,91.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
4,001,I11300000005,NaN,2024-01-01 01:00:19,Y,2024-01-01 01:12:33,C,79.0,F,12.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88934,001,I11400060735,NaN,2025-12-31 22:48:10,Y,2025-12-31 23:07:50,C,52.0,F,19.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
88935,001,I11400060736,NaN,2025-12-31 22:58:58,Y,2025-12-31 23:11:45,A,75.0,F,12.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
88936,001,I11400060737,NaN,2025-12-31 23:16:21,Y,2026-01-01 02:54:13,C,25.0,F,217.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
88937,001,I11400060738,NaN,2025-12-31 23:19:33,Y,2025-12-31 23:45:35,A,82.0,F,26.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN
88938,001,I11400060739,NaN,2025-12-31 23:42:39,Y,2026-01-01 00:30:57,A,38.0,F,48.0,...,NaN,N,NaN,N,NaN,N,N,NaN,3,NaN

In [5]:
table6 = pd.read_csv('table6_clear.csv', encoding='big5')

In [6]:
table6.columns

Index(['ACCOUNTNO', 'Hb', 'WBC', 'Ht', 'PLT', 'Lymphocyte', 'Neutrophil Seg.',
       'Absolute Neutrophil count', 'Na', 'K', 'Creatinine', 'GPT', 'CRP',
       'HST', 'Leukocyte level', 'Nitrite level', 'Bacteria level',
       'Microscopic RBC level', 'Microscopic WBC level', 'PH',
       'Influenza Virus A level', 'T.Bilirubin', 'PT', 'INR', 'APTT', 'PCO2',
       'HCO3', 'BE(ecf)', 'O2 SAT', 'FIRST_ORDERTIME'],
      dtype='object')

In [7]:
table1['INTIME'] = pd.to_datetime(table1['INTIME'])
table6['FIRST_ORDERTIME'] = pd.to_datetime(table6['FIRST_ORDERTIME'])

# 2. 計算時間差 (StayTime)
# 結果會是一個 Timedelta 物件 (例如: 0 days 02:30:00)
table1['StayTime'] = table6['FIRST_ORDERTIME'] - table1['INTIME']

# 3. 如果你想將 StayTime 轉換為「小時」或「分鐘」的小數值（方便跑統計或畫圖）
table1['StayTime_hours'] = table1['StayTime'].dt.total_seconds() / 3600

In [8]:
len(table1),len(table1['ACCOUNTNO'].unique())

(88938, 88938)

In [9]:
table1.columns

Index(['DIVISIONNO', 'ACCOUNTNO', 'IPDACCOUNTNO', 'INTIME', 'ISEMGOUT',
       'EMGOUTTIME', 'ROOMNO', 'AGE', 'SEX', 'STAYTIME', 'ISIPD', 'IPDINTIME',
       'ISICU', 'ICUTIME', 'ISDEATH', 'DEATHTIME', 'ISBOOKICU', 'ISTRANS',
       'TRANSTIME', 'NHIDISCHARGECODE', 'IPDNHIDISCHARGECODE', 'StayTime',
       'StayTime_hours'],
      dtype='object')

In [10]:
table1_clear = table1[['ACCOUNTNO','ROOMNO', 'AGE', 'SEX', 'StayTime_hours', 'INTIME']]

In [13]:
table1_clear.to_csv('table1_clear.csv', index=False)

In [12]:
table1_clear

          ACCOUNTNO ROOMNO   AGE SEX  StayTime_hours              INTIME
0      I11300000001      C  57.0   F        0.167500 2024-01-01 00:44:57
1      I11300000002      A  65.0   M        0.261944 2024-01-01 00:47:17
2      I11300000003      C  48.0   F        0.460833 2024-01-01 00:50:21
3      I11300000004      A  21.0   F        0.397778 2024-01-01 00:57:08
4      I11300000005      C  79.0   F        0.694722 2024-01-01 01:00:19
...             ...    ...   ...  ..             ...                 ...
88934  I11400060735      C  52.0   F             NaN 2025-12-31 22:48:10
88935  I11400060736      A  75.0   F             NaN 2025-12-31 22:58:58
88936  I11400060737      C  25.0   F             NaN 2025-12-31 23:16:21
88937  I11400060738      A  82.0   F             NaN 2025-12-31 23:19:33
88938  I11400060739      A  38.0   F             NaN 2025-12-31 23:42:39

[88938 rows x 6 columns]